### PR TITLE
Nt/username autocomplete

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
Allows searching of accounts in editor if word starts with '@'. There are lots and lots of corner cases, I have tried to cover all, feel free to test and provide feedback or any bugs you come across

Everything search related is processed inside `usernameAutofillBar` component. For inserting user in editor text, introduced a helper method `applyUsername` that handles placement and selection update.

This PR covers username search only, not post path search yet.

### Where should the reviewer start?
`usernameAutofillBar.tsx`

### Steps to reproduce
Start adding username anywhere in editor, requires minimum 2 characters after @

### Issue
https://trello.com/c/LQB2l83j/315-username-finder-in-editor

### Screenshots/Video
https://user-images.githubusercontent.com/6298342/151389937-d0d4046a-ef36-423d-93f0-329e7f1d53d1.mov

### CODE REVIEW

**Comment by noumantahir** [comment]
@feruzm any feedback on this PR so far...?

**Comment by feruzm** [comment]
@noumantahir it looks great only thinking how we will add path finding or we won’t add that to mobile app 🤔

**Review by feruzm — APPROVED** [review]
Lgtm, could you decrease denounce to 200 ms?!

**Comment by noumantahir** [comment]
> @noumantahir it looks great only thinking how we will add path finding or we won’t add that to mobile app 🤔

Not suitable in this arrangement, will have to think of something else

**Comment by noumantahir** [comment]
> Lgtm, could you decrease denounce to 200 ms?!

done.

**Pull request merged**
