### PR TITLE
added post shcedule status icon in posts schedules tab

### LINKED ISSUE #2162: Improve: show scheduled post status
Show appropriate status with scheduled posts.  right now the schedules UI do not show any status.

Status Codes:
Screenshot_2022-01-27_at_19 32 12

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
This PR adds post schedule status in posts schedules tab.

### Where should the reviewer start?
Go to drafts screen and then to schedules tab.

### Issue number
fixes #2162 

### Screenshots/Video
image

### CODE REVIEW

**Review by noumantahir — CHANGES_REQUESTED** [review]

**Comment by aliseyalvi** [comment]
@noumantahir 

- added enum type for schedule status
- added popover tootip for status icon
image

**Review by noumantahir — APPROVED** [review]
lgtm

**Comment by noumantahir** [comment]
@feruzm awaiting your approval before merge...

**Review by feruzm — APPROVED** [review]
👍

**Pull request merged**
