### PR TITLE
batch delete drafts

### LINKED ISSUE #2676: batch delete drafts
Ability to select multiple draft entries and delete with single button.... User interaction flow also need discussing.

ref: https://discord.com/channels/385034494555455488/385448617084846085/1042791986484232233

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
added batch delete drafts and schedules functionality.
User can longpress on a draft or schedule and a delete button would appear in header which delete multiple drafts selected in one go

### Issue number
fixes #2676 

### Screenshots/Video

https://github.com/ecency/ecency-mobile/assets/48380998/8862b83e-3494-4937-8d14-ff8bfcea9207

### CODE REVIEW

**Review by noumantahir — CHANGES_REQUESTED** [review]
perhaps we can try adding blue or red border border of selection item instead of painting it blue all along, also 

as for delete button, either we can make the top bottom red or using the delete button component from this modal in video. either would be good
https://github.com/ecency/ecency-mobile/assets/6298342/2813450f-e7b2-4957-a08f-bbad45810a15

**Comment by aliseyalvi** [comment]
https://github.com/ecency/ecency-mobile/assets/48380998/e8ea76fc-7d0a-4051-9000-8cc643be7ad8

**Comment by noumantahir** [comment]
> Monosnap.screencast.2023-07-25.20-41-03.mp4

seems good, only change top delete button color to $pureWhite should work for both dark and light theme..

**Comment by noumantahir** [comment]
@aliseyalvi more feedback on this... 

Long press draft entry delete button should also initiate batch delete selection process

If I delete a pre selected draft item, and then batch delete drafts, it throws a failure toast, which does not affect the functionality but confuses users..

Another feedback regarding selection mark, perhaps red border is still too much, may be make the draft entry delete button on red instead. tapping delete button to deselect should also fix the above mentioned issue.

Last, change top batch delete button icon color to white...

https://github.com/ecency/ecency-mobile/assets/6298342/c95df8c3-b684-4f89-947d-645bc36aef22

**Comment by aliseyalvi** [comment]
@noumantahir PR updated. 

https://github.com/ecency/ecency-mobile/assets/48380998/48a2b7b8-7cca-41de-89b8-29f72a8930a8

**Comment by noumantahir** [comment]
> @noumantahir PR updated.
> 
>  Monosnap.screencast.2023-08-09.13-12-25.mp4

match color, if possible reuse this delete button as component and move it under components/atoms directory if not already there... if not smoothly possible just update color.

Screenshot 2023-08-09 at 1 52 20 PM

**Comment by aliseyalvi** [comment]
@noumantahir reverted delete icon color to primaryBlack as uploadGalleryModal is also using the same color 
image
image

**Comment by aliseyalvi** [comment]
image
image

**Review by noumantahir — APPROVED** [review]
lgtm 
@feruzm please review and merge

###video
https://github.com/ecency/ecency-mobile/assets/6298342/05ba5cb4-7d46-45e3-9110-44e7d9afa000

**Pull request merged**
