### PR TITLE
Quick Comment Expansion to other places 

### LINKED ISSUE #2258: Improve: quick comment expansion
Right now quick comment is limited to only one button while all other places open full editor, we should open quick comment modal as first place to make a comment and an expansion button should open full comment editor.

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
fixes #2258.
This PR adds quick comment modal in post screen and in comments as well. 
Added expand icon to go to full screen editor inside quick reply modal

### Issue number
#2258 

### Screenshots/Video
**_Updated demo - 21 April_**

https://user-images.githubusercontent.com/6298342/164343093-eacfac9d-ed30-44a2-841a-04eec5be3613.mov

_**Archived Demo**_
https://user-images.githubusercontent.com/48380998/163668315-691fa330-10c9-4c96-a4ea-ccb5dd37c3cb.mp4

### CODE REVIEW

**Review by noumantahir — CHANGES_REQUESTED** [review]
Three things need updating before I can continue my review...

1. In comment reply, the body is not passed to modal.
2. When expanding modal to editor, existing editor text should pass to full editor.
3. on expansion, full editor should show keyboard with cursor at end of comment text.

Screenshot 2022-04-17 at 12 59 57 AM

**Comment by aliseyalvi** [comment]
> Three things need updating before I can continue my review...
> 
> 1. In comment reply, the body is not passed to modal.
> 2. When expanding modal to editor, existing editor text should pass to full editor.
> 3. on expansion, full editor should show keyboard with cursor at end of comment text.
> 
> Screenshot 2022-04-17 at 12 59 57 AM

@noumantahir 

1. actually we are rendering post summary in modal header and in case of comment reply summary is missing and hence not shown. What we should show in case of comment reply?
2. regarding passing text we didn't implemented this functionality, will implement that.

**Comment by aliseyalvi** [comment]
@noumantahir 

1. added post title when replying comments as we dont have any other data to show when replying comments.https://github.com/ecency/ecency-mobile/pull/2267/commits/c1d027689f147ae0a204b01475ef391ad8b43083
2. comment text can be passed on to full editor now when typing in quick reply modal, also sets cursor postion to end of text. https://github.com/ecency/ecency-mobile/pull/2267/commits/607fc807a29b82054af7eed67861187a0ceb4386
3. also fixed a bug causing crash when commenting in full editor https://github.com/ecency/ecency-mobile/pull/2267/commits/38c366ecf540162dc1098b534636f4af0d833ba1

**Comment by noumantahir** [comment]
> actually we are rendering post summary in modal header and in case of comment reply summary is missing and hence not shown. What we should show in case of comment reply?

@aliseyalvi what you can do is, when modal or editor is opened, check if summary property exist, if it does not extract summary and show that... 

Example
`const headerText = post.summary || postBodySummary(post, 150, Platform.OS);`

**Comment by aliseyalvi** [comment]
> > actually we are rendering post summary in modal header and in case of comment reply summary is missing and hence not shown. What we should show in case of comment reply?
> 
> @aliseyalvi what you can do is, when modal or editor is opened, check if summary property exist, if it does not extract summary and show that...
> 
> Example `const headerText = post.summary || postBodySummary(post, 150, Platform.OS);`

@noumantahir actually the issue with this approach is that, when u will see the code u will see that we are passing relative post to the modal where comment button is pressed, so when comment is pressed in post body or post bottom tabbar the post content is actually the parent post, but when we tap comment button inside comment replies section the content of post becomes content of comment, and that doesn't contain any title or summary etc, we just have body of the comment not the parent post, so we can't use the title of parent post or its summary as the content for post props changes when it comes to renderring comments. Hope it does make sense.

**Comment by noumantahir** [comment]
@aliseyalvi reply to reply is not working, check the video below.

https://user-images.githubusercontent.com/6298342/164342274-0b70dd17-54ca-4680-9bc7-583a412d6685.mov

**Review by noumantahir — APPROVED** [review]

**Comment by noumantahir** [comment]
Tested well and added an updated demo in PR description.... lgtm!

**Review by feruzm — APPROVED** [review]
Lgtm

**Pull request merged**
