### PR TITLE
Nt/buy account

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
- Implemented UI for buying account
- passing email address as meta to ecency on successful account purchase
- support for deep link QR account purchase

### Issue number 
#2470

### Screenshots/Video
Screenshot from 2022-12-22 03-22-19
Screenshot from 2022-12-22 03-22-07

### CODE REVIEW

**Comment by noumantahir** [comment]
@feruzm need text suggestions for paid and unpaid accounts accounts 

Screenshot from 2022-12-22 03-22-19

**Comment by feruzm** [comment]
@noumantahir 

Free accounts:
Get a full-fledged Hive account, this method has basic checks to make sure botnet doesn't abuse our signup faucet.

Premium accounts:
Get a full-fledged, premium Hive account with no extra checks and few perks such as:
 - instant creation without extra checks and waiting
 - 3x RC compared to normal new accounts
 - 300 Points to help you get started

**Comment by noumantahir** [comment]
Update look...

Screenshot 2022-12-29 at 11 24 18 PM
Screenshot 2022-12-29 at 11 25 26 PM

**Review by feruzm — APPROVED** [review]
🚀

**Pull request merged**
