### PR TITLE
Parse comma separated input

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
This PR fixes the comma parsing in powerdown screen

### Screenshots/Video

https://user-images.githubusercontent.com/48380998/170729426-cb19b8cc-d0be-40ed-8274-2119e1f71279.mp4

### CODE REVIEW

**Comment by aliseyalvi** [comment]
@noumantahir Update:
Parsing amount input similar to delegation screen.
Also added keyboard taps persistance and return keytype to done

https://user-images.githubusercontent.com/48380998/170738720-977c3b1d-18a4-4bce-9151-354d33207d49.mp4

**Review by noumantahir — APPROVED** [review]
LGTM!

**Comment by noumantahir** [comment]
@feruzm tested well, I also merged one of my relevant branch with it. you may review before merge....

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
