### PR TITLE
Nt/spk

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
Added support for tracking SPK assets....some features added include....

- Adding spk larynx assets to wallet list along with ordering
- Basic asset information with some extra information related to larynx power in assets details
- Support for actions include, transfer, power up, power down, delegate to node runners

### Where should the reviewer start?
Add spk/larynx assets from assets selection screen/modal under wallet screen

### Issue number
https://github.com/orgs/ecency/projects/2#card-87596832

### Screenshots/Video
Screenshot 2023-04-03 at 1 26 44 AM
Screenshot 2023-04-03 at 1 26 53 AM
Screenshot 2023-04-03 at 1 26 59 AM
Screenshot 2023-04-03 at 1 27 07 AM

### CODE REVIEW

**Comment by noumantahir** [comment]
@feruzm some queries....

1. Will this SPK logo suffice or use different for SPK and LARYNX
2. Should LARYNX be treated as separate entry like done in web or merge within LARYNX token details page

**Comment by feruzm** [comment]
@noumantahir 
1. Logo looks good to me
2. LARYNX and LARYNX POWER could be separated because operations each staked and unstaked token can do differ.

**Comment by noumantahir** [comment]
Hooked up larynx power
Screenshot 2023-04-03 at 4 53 09 AM
Screenshot 2023-04-03 at 4 53 05 AM

**Comment by noumantahir** [comment]
updated and tested all integrated spk transactions using hive signer.

Screenshot 2023-05-03 at 4 26 43 PM

**Review by feruzm — APPROVED** [review]
lgtm, after some testing we can improve if needed.

**Pull request merged**
