### PR TITLE
transfer screens update

### LINKED ISSUE #2370: Update transfer screens UI/UX to follow design language of Delegate screen
Create Reuseable components for transfer screen. Extend delegate screen and powerdown screen UI to other Transfer Screens

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
This PR updates the design of transfer screens according to design of delegate screen. For now I had just moved the same parts from transfer screen to separate components and updated the UI style as used in delegate screen. Functionality is still dependent on code in transfer screen.
Note: Promote and Boost screen is not updated as they had different design than the other transfer screens

### Issue number
fixes #2370 

### Screenshots/Video

https://user-images.githubusercontent.com/48380998/179895403-b98e6526-ec10-4d23-a668-498a56d29ae2.mp4

### CODE REVIEW

**Review by noumantahir — COMMENTED** [review]
I like the single reused component approach, we can use the same component for delegation side as in next iterations..

As for changes required....

- [ ]  Match labels colors with ones used in delegation screen, screenshot 1

- [x]  Reduce gap between label and input to half of current, push balance labels to right of screen, also screenshot 1

- [ ]  Add title and subtitle to second section/card, screenshot 2... 

   **Section 1 Title:** Account Details
   **Section 1 Description:** Operations related to funds are irreversible, make sure receivers username is correct
   **Section 2 Title:** Transfer Details
   **Section 2 Description:** Enter transfer amount within maximum available balance and must be greater than 0.001

- [ ]  If possible use single account selection for GET POINTS like used in convert page but with To user selection as esteem app even if From account is changed, screenshot 3 

_Screenshot 1_
Screenshot 2022-07-20 at 1 04 08 PM

_Screenshot 2_
Screenshot 2022-07-20 at 1 24 45 PM

Screenshot 3
Screenshot 2022-07-20 at 1 46 41 PM

**Comment by noumantahir** [comment]
Screenshot 2022-07-22 at 4 12 11 PM
Screenshot 2022-07-22 at 4 04 52 PM
Screenshot 2022-07-22 at 4 05 10 PM
Screenshot 2022-07-22 at 4 04 42 PM
Screenshot 2022-07-22 at 4 03 41 PM

**Review by noumantahir — APPROVED** [review]
@feruzm seems all good to me, you may review and merge..

Screenshot 2022-07-22 at 4 05 10 PM
Screenshot 2022-07-22 at 4 04 52 PM
Screenshot 2022-07-22 at 4 04 42 PM
Screenshot 2022-07-22 at 4 03 41 PM
Screenshot 2022-07-22 at 4 12 11 PM

**Comment by noumantahir** [comment]
@feruzm updated keybaord aware view and tested on both android and ios

**Review by feruzm — APPROVED** [review]
Lgtm, will do on device tests as well

**Pull request merged**
