### PR TITLE
Bug Fix: Beneficiaries not showing correctly

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
Filtered the default beneficiary from beneficiaries list while saving draft and saving beneficiaries list in redux.
Add default beneficiary when draft is loaded
This removes the inconsistancy caused by draft saved in ecency web as in ececny web it does not saves the default beneficiary but on mobile it was saving default beneficiary in meta. That was causing inconsistancy.

### Issue Number
https://discord.com/channels/@me/920267778190086205/1009051563953758238

### CODE REVIEW

**Comment by aliseyalvi** [comment]
When we set schedule date on ececny web it saves schedule successfully but when we fetch it on ececny mobile it doesn't return schedule data in meta. It should be fixed on backend to work on ecency mobile . Refer screenshots 
image
image
image

**Comment by noumantahir** [comment]
apparently adding schedule date in post settings, hide the ability to save draft... check` Update Draft` button is hidden 
Screenshot 2022-08-17 at 1 27 53 PM

**Comment by aliseyalvi** [comment]
Removed schedule info from meta and other code related to it done in past [PR](https://github.com/ecency/ecency-mobile/pull/2356/commits/31ee6ef52fe72a00412bded6d860731148c94816#diff-dc85daf1859ed31aa72bfb8377a211eb6b311d04480caa009a9953b5b319b8aa) 

Refer commits:
https://github.com/ecency/ecency-mobile/pull/2425/commits/0c6c7d09ad070402931ef5b7a77ae5bcaf44617b
https://github.com/ecency/ecency-mobile/pull/2425/commits/a23b1678ddd7bbef1fe659adeee5f58c42bf90d7
https://github.com/ecency/ecency-mobile/pull/2425/commits/05eeda6193888ead73d6f67a63e47526c06ac7ef

**Review by noumantahir — APPROVED** [review]
lgtm

**Review by feruzm — APPROVED** [review]

**Pull request merged**
