### PR TITLE
Nt/engine tokens

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
Added support for engine tokens
Exclusive modal for tracking specific owned tokens
Showing history graph for tokens
Showing and claiming rewards to individually tracked tokens
Support for staking, delegating, transfer, undelegate and unstaking

### Issue number
https://github.com/orgs/ecency/projects/2#card-80685358

### Screenshots/Video
Screenshot 2022-10-07 at 7 13 56 PM

### CODE REVIEW

**Comment by noumantahir** [comment]
@feruzm need some guidance on what should the preferable flow for engine tokens....

- what tokens should appear by default for all users.
- what should be the claim rewards flow
- do we need to render price history charts, I believe it's value is locked with hive values

**Comment by feruzm** [comment]
@noumantahir 

Each token on Engine has almost same functionality like HIVE token. It can be powered up/down (un/staked), delegated, transferred, etc. 
* Token details will show power up/down balances, delegated balances, liquid balances that's available for transfer
* Tokens page will show only user selected ones, we can bounce a little and show button to catch attention and tell they can enable more tokens on this screen.
* Their prices are not pegged to HIVE, those also have market driven value and prices, hive-engine.com has market page, leodex.io and other's use same market data, so I believe we can get price chart/history. Need checking/research.
* Claim reward flow, we can show unread type of icon on token listing if it has pending unclaimed reward, so person can open token details page and claim that reward individually, later we will think about claiming multiple at once.

Let me know if something else I forgot to cover.

**Comment by noumantahir** [comment]
Update: 
- Unclaimed rewards
- Claiming Unclaimed rewards
-Integrated Engine Token Actions

Pending
- Update Engine Header UI in main wallet screen - **Suggestion Required**

Screenshot from 2022-11-29 20-03-55
Screenshot from 2022-11-29 20-02-11
Screenshot from 2022-11-29 20-02-40
Screenshot from 2022-11-29 20-02-32
Screenshot from 2022-11-29 20-07-26

**Comment by noumantahir** [comment]
feedback from feruz
Screenshot 2022-12-13 at 3 41 40 PM

**Comment by noumantahir** [comment]
@feruzm regarding Power Down and Staking consistency... I think staking is more acceptable around crytos, keeping that in mind and the fact users are used to Hive powering concepts... how about this middle ground....

Screenshot 2022-12-13 at 5 48 53 PM
Screenshot 2022-12-13 at 5 48 29 PM
Screenshot 2022-12-13 at 5 48 05 PM

**Comment by feruzm** [comment]
@noumantahir Smart, I like it.

**Comment by noumantahir** [comment]
Screenshot from 2022-12-17 03-03-25
[Screencast from 16-12-2022 23:36:15.webm](https://user-images.githubusercontent.com/6298342/208196789-d2f22d96-d2e6-4ea9-ab35-954587595333.webm)

**Comment by noumantahir** [comment]
engine claim flow demo
https://user-images.githubusercontent.com/6298342/208661550-d2eee460-ace4-4460-9219-bd1c59b9f6ba.mov

**Comment by noumantahir** [comment]
Screenshot 2022-12-20 at 6 12 55 PM

**Review by feruzm — APPROVED** [review]
lgtm, great job. Let's do some tests 👍

**Pull request merged**
