### PR TITLE
Bug Fix: app not rendering properly on android tablets 

### LINKED ISSUE #2449: BUG: android app installed on chromebooks not rendering properly
Happens when opening app using an external post link.

Screenshot 2022-09-07 at 7 50 26 PM

Issue might be due landscape/portraint width not calculating properly. Need to reproduce it first

**Update:**
Attempted to reproduce this issue on android table emulator, apparently it is not being reproduce even if we open Ecency app while tablet is locked in landscape mode.

Screenshot 2022-09-23 at 5 19 12 PM

If we notice closely look at the first screenshot shared by melinda, the **BasicHeader** dimensions are being read properly but it messes up as it renders **PostBodyView**. Based on this deduction, the issue seems to be coming from this code linked below, it is just a guess though
https://github.com/ecency/ecency-mobile/blob/development/src/utils/getWindowDimensions.ts#L18

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
In this PR, device info is got at app startup and if device is android tablet then it is locked in the orientation in which app was launched. This fixes the issue of inappropriate layout on android tablets due to msicalculation of dimensions due to change in layout/orientation after app startup. It was the qucikest and easy fix for now to handle issue which was affecting some devices 

### Issue number
fixes #2449

### CODE REVIEW

**Comment by aliseyalvi** [comment]
###Before
https://user-images.githubusercontent.com/48380998/194771409-85d63240-363f-4eb5-b2e6-b8aa1e9db409.mp4

**Comment by aliseyalvi** [comment]
### After
https://user-images.githubusercontent.com/48380998/194771508-7cce4f5f-898e-4de5-a8c7-e6af4589fb5d.mp4

**Comment by aliseyalvi** [comment]
> > ### After
> > Monosnap.screencast.2022-10-09.22-42-22.mp4
> 
> seems the trick we discussed actually worked...:D Have you tried launching in portrait mode as just to verify that part is also working as expected.

yes prtrait is also working and this trick is only applied to android tablets, all rest of devices would follow previous method

**Review by noumantahir — APPROVED** [review]
this should serve us well temporarily uptill we do not fully support dynamic orientation change.

**Review by feruzm — APPROVED** [review]
lgtm

**Pull request merged**
