### PR TITLE
user name validation checks in register screen

### LINKED ISSUE #2659: add validity check for username during registering to not allow `_` in username
add validity check for username during registering to not allow `_` in username... for instance `nomo_90c` is not a valid username because it includes underscore, but app checks it as valid username and user can proceed with premium account purchase causing embarrassment for us.

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?
Added user name validation checks in register screen

### Issue number
fixes #2659 

### Screenshots/Video

https://user-images.githubusercontent.com/48380998/226172557-a874124d-25de-4a52-b70a-502b9ca005e6.mp4

### CODE REVIEW

**Review by noumantahir — CHANGES_REQUESTED** [review]
let spend some more time with in making the experience more intuitive and helpful for user

**Comment by noumantahir** [comment]
**Change Requests**

1. When user first enters the SignUp screen, the username and email fields are red by default, try to make them white when fields are empty. I believe it was functioning this way before but some update might have messed it up.

Screenshot 2023-03-20 000940

2. As suggested by @aliseyalvi, if username is incorrect we should show red button instead of x (icon can be red exclamation mark enclosed in a circle), tapping on it should reveal popover with description, it can either contain the description of issue with user typed name or may just contain complete rules if they can be kept brief like...
> Use alphanumeric characters, avoid special characters like _ , --
@feruzm please suggest any

Screenshot 2023-03-20 001638

3. Keep the default `@` icon displayed as fallback when user avatar is not present both for valid and invalid usernames. current behavior hides the icon making an awkward white space.
Screenshot 2023-03-20 001756

**Comment by aliseyalvi** [comment]
@noumantahir 

- disabled red border highlight on start
- show user avatar if user exist, show @ as fallback for all other conditions
- added red error info icon and wrapped with popover to show error description in tooltip

https://user-images.githubusercontent.com/48380998/226983548-00997884-6e54-4520-811b-b3d75347f5d4.mp4

**Comment by noumantahir** [comment]
@aliseyalvi 2 minor changes... 

1. try using `info-outline` icon instead of using filed red icon.
2. when user starts typing the error appears instantly which might offend users, try adding a 500 ms delay in callback processing just like we do with a number of text inputs using `debounce` from `loadash`, check example in MarkdownEditorView `_debouncedOnTextChange` if needed

https://user-images.githubusercontent.com/6298342/227517206-17746f56-8b7f-4006-8aeb-335e34ee3dc2.mov

**Comment by aliseyalvi** [comment]
https://user-images.githubusercontent.com/48380998/227599113-815fd3aa-f886-49ab-ad2e-a2cbc05ea7a6.mp4

**Review by noumantahir — APPROVED** [review]
seems good enough now... lgtm

**Pull request merged**
