### PR TITLE
Cached Tabs

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
- caches tab posts as they are fetched.
- saves latest posts from friends or hot tab to show to user on next app session.
- It also fixes the bug we detected earlier, tab data being linked to wrong filter on tab change.

### Where should the reviewer start?
- There is a useReducer implementation in postsContainer.

### Known issues
- If you login, the friends tab loads up but do not render until you change tab, should be simple to fix
- Scrolling one tab also appear to scroll other tabs, essentially because it is a single component
- There is a momentary lag when changing tab, may or may not affect end user, it can be further avoided by optimising list items and maintaining separate components for each 

### Important
- This is an initial experimental code push, please do test this out thoroughly 
- Code quality is not the best, but is just for testing purposes... I will be making a separate reducer section under posts component

Looking forward to feedback of cached-tabs update so far.

### CODE REVIEW

**Comment by feruzm** [comment]
@noumantahir 

Beside your known issues, here is what I noticed

1. Changing user to another didn't refresh the Feed (friends/communities) probably related to issue you mentioned.
2. Pull down to refresh on Feed (fr./com.) sections sometimes keep showing loader
3. Voting on post and changing tabs, shows old cache for item (not voted and less vote count)

Are we doing background fetch to update cache?

Other than that, I think, it is really good experience to have feed right away when you open app

**Comment by noumantahir** [comment]
Thank you for pointing out.As for background refresh, what I am planning is adding an interval callback to check for new posts every few minutes, either for any one or all feed tabs.What this reducer structure that should be easy to manage.On 6 Mar 2021 09:10, Feruz M <notifications@github.com> wrote:
@noumantahir
Beside your known issues, here is what I noticed
Changing user to another didn't refresh the Feed (friends/communities) probably related to issue you mentioned.Pull down to refresh on Feed (fr./com.) sections sometimes keep showing loaderVoting on post and changing tabs, shows old cache for item (not voted and less vote count)
Are we doing background fetch to update cache?
Other than that, I think, it is really good experience to have feed right away when you open app

**Comment by noumantahir** [comment]
Re: feed right away when you open app.I tried to follow Facebook's approach of only storing first tab for later sessions... We can do that for all feed screen tabs as well, just did not want to make it look like an overkill.Let me knowOn 6 Mar 2021 09:10, Feruz M <notifications@github.com> wrote:
@noumantahir
Beside your known issues, here is what I noticed
Changing user to another didn't refresh the Feed (friends/communities) probably related to issue you mentioned.Pull down to refresh on Feed (fr./com.) sections sometimes keep showing loaderVoting on post and changing tabs, shows old cache for item (not voted and less vote count)
Are we doing background fetch to update cache?
Other than that, I think, it is really good experience to have feed right away when you open app

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Re

**Comment by noumantahir** [comment]
FIXED: If you login, the friends tab loads up but do not render until you change tab, should be simple to fix
FIXED: Scrolling one tab also appear to scroll other tabs, essentially because it is a single component
FIXED: Changing user to another didn't refresh the Feed (friends/communities) probably related to issue you mentioned.
FIXED: Pull down to refresh on Feed (fr./com.) sections sometimes keep showing loader

IN_PROGRESS: Voting on post and changing tabs, shows old cache for item (not voted and less vote count)

**Comment by noumantahir** [comment]
FIXED: Voting on post and changing tabs, shows old cache for item (not voted and less vote count)

**Comment by noumantahir** [comment]
FEATURE ADDITION: Latest post fetch v1

- Added support for latest post check after 30 seconds (for testing) of last created post...
- If there are new posts user is prompted to refresh posts, which can be skipped.
- If user change tabs or refresh tab manually the timer is reset

LATER UPGRADE:
once well tested, it can be easily upgraded to show profile bubbles for new posts and using prefetched posts data instead fetching a fresh copy

**Comment by noumantahir** [comment]
Pending Stuff:

1. bypassing pinned communities while checking for new posts if they are more than 5.... if less than 5, things should be fine

2. use pre-cached new posts when popup is tapped instead of refreshing and fetching posts again.

**Comment by noumantahir** [comment]
For reference: intl translation id for popup label Posted is `home.popup_postfix`

**Review by feruzm — APPROVED** [review]
looks good so far, let's merge and do final tests before release!

**Pull request merged**
