### PR TITLE
Nt/reply modal tweaks

### PR DESCRIPTION
**Pull request by noumantahir**
### What does this PR?
Minor tweaks that should improve quick reply, please do give it a shot as well. Will be redoing it as well after we are done with critical issues we are facing.

PR merges another relevant branch from @aliseyalvi as well.

### Issue number
#2311

### Screenshots/Video
Screenshot 2022-05-29 at 3 57 59 PM

### CODE REVIEW

**Comment by aliseyalvi** [comment]
@noumantahir 

- I have added the content of quick reply modal into child component and put the portal back as Higher Order Component which solves the initial cursor jumping issue due to which we have removed the portal but that raised Keyboard Taps Persistance issue. This would solve both issues . check this commit https://github.com/ecency/ecency-mobile/pull/2328/commits/a45ed69017aa1b1a05cd96fa7c47997b99deca50
- in this commit added check for navigation params which was cuasing error when comment is done in full editor when naigating from quick reply to full editor through expand btn https://github.com/ecency/ecency-mobile/pull/2328/commits/83cf0f89ac8595cb50f784b12e53eacc9f4824fa

**Comment by noumantahir** [comment]
@aliseyalvi apparently keyboard is not auto opening in android... also try if you can set separate bottom paddings for keyboard opened and close...

**Comment by aliseyalvi** [comment]
> is keyboard not opening in quick reply modal or when navigating to full editor for reply?

@noumantahir I had tried to update the bottom padding based on keyboard opening and closong but it is showing a weired behaviour. I mean this is not smooth and shows a jerk when changing padding. See the screen record 

https://user-images.githubusercontent.com/48380998/171040884-ba33e285-4004-48f3-ae1b-ac20b0e89186.mp4

**Comment by noumantahir** [comment]
> > @aliseyalvi apparently keyboard is not auto opening in android... also try if you can set separate bottom paddings for keyboard opened and close...
> 
> is keyboard not opening in quick reply modal or when navigating to full editor for reply? I had tested on my device and keyboard is opening on both quick reply modal and full editor as well

perhaps it was emulator issue, tested on my phone instead of emulator, working fine

**Comment by noumantahir** [comment]
@feruzm this can be tested and merged now... the primary change is now user do not have to close modal before approving reply while the input glitch is no longer affecting us.

**Review by feruzm — APPROVED** [review]
Lgtm, let’s see if Portal doesn’t cause issue on iPhone again

**Pull request merged**
