### PR TITLE
[Bug Fix] Auth screens images issues

### LINKED ISSUE #2632: Mobile: Sign-in & Sign-up screen images do not fit on the screen
Tested on Android and iOS

image

image

### PR DESCRIPTION
**Pull request by aliseyalvi**
### What does this PR?

- Fixed image clipping issue in register screen
- Fixed image clipping issues in signin screen

### Issue number
fixes #2632 

### Screenshots/Video
image
image

### CODE REVIEW

**Review by noumantahir — CHANGES_REQUESTED** [review]
Reducing the side of mascots might not be a good idea here, please check the positioning and size of mascots on various different screen sizes and devices to see if it looks good on all

**Comment by feruzm** [comment]
@aliseyalvi also please make sure both mascots are same size/visibility wise.

**Comment by aliseyalvi** [comment]
@noumantahir @feruzm I had changed mascots dimensions to percentages and its parent container to flex so it would be least affected by device dimensions.

image
image

**Comment by noumantahir** [comment]
@aliseyalvi regarding sign in mascot, cannot we reduce the percentage assigned to make the both look somewhat the same size... from UI perspective, the sign in mascot looks too big for the text content on left.... 

Do also share screenshots of both on different simulators like iPhone 6, nexus 5, pixel 3a as well

**Comment by aliseyalvi** [comment]
image
image
image
image

**Comment by aliseyalvi** [comment]
image
image
image
image

**Review by noumantahir — APPROVED** [review]
good work

**Review by feruzm — APPROVED** [review]

**Pull request merged**
